title: KenkōDō avec Inna
contact_action: https://formspree.io/xyyjkzrj
default_locale: "fr"
tagline: Yoga Vinyasa et Yin & Do-In sur Romans, Valence et environs
description: KenkōDō avec Inna vous propose des activités autour du bien-être. Des cours de Vinyasa Yoga, Yin Yoga et Do-In vous sont proposés sur Romans, Valence et les environs.

email: contact.kenkodo@gmail.com
url: https://www.kenkodo.fr
lang: "fr_FR"

kramdown:
  html_to_native: true

social:
  name: KenkōDō
  links:
    - https://www.facebook.com/kenkodo.yogadoin

plugins:
  - jekyll-feed
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-sitemap

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

include: ['.htaccess']

responsive_image:
  template: _includes/responsive-image.html
  output_path_format: assets/resized/%{width}/%{basename}
  cache: true
  sizes:
    - width: 320
    - width: 480
    - width: 800
    - width: 1024
    - width: 1440
    - width: 1920
    - width: 2560
